baseURL: 'https://sposusu.github.io'
languageCode: 'en-us'
title: 'Hussar place'
description: 'Record the exploration'
theme: 'congo'

defaultContentLanguage: 'en'
enableRobotsTXT: true
summaryLength: 0

# Site settings
params:
  description: 'Record the exploration'
  author: 'Hussar'
  
  # Congo theme settings
  colorScheme: "congo"
  defaultAppearance: "light"
  autoSwitchAppearance: true
  
  enableSearch: true
  enableCodeCopy: true
  enableImageLazyLoading: true
  enableImageWebp: true
  enableQuicklink: true
  
  # Analytics
  googleAnalytics: 'G-433XCR65EL'
  
  # Comments
  disqus:
    shortname: 'demowebsite'
  
  # Header
  header:
    layout: "basic"
    showTitle: true
  
  # Footer
  footer:
    showCopyright: true
    showThemeAttribution: true
    showAppearanceSwitcher: true
    showScrollToTop: true
  
  # Homepage
  homepage:
    layout: "page"
    showRecent: true
    recentLimit: 6
  
  # Article
  article:
    showDate: true
    showDateUpdated: false
    showAuthor: true
    showBreadcrumbs: true
    showDraftLabel: true
    showHeadingAnchors: true
    showPagination: true
    showReadingTime: true
    showTableOfContents: true
    showTaxonomies: true
    showWordCount: false
    showComments: false
  
  # List
  list:
    showBreadcrumbs: true
    showSummary: true
    showTableOfContents: false
    showTaxonomies: true
    groupByYear: false
    paginationWidth: 1
  
  # Taxonomy
  taxonomy:
    showTermCount: true
  
  # Main site author (Congo format)
  author:
    name: "Hussar"
    image: "images/logo.png"
    headline: "Record the exploration"
    bio: "Welcome to Hussar place - a space for recording exploration and discoveries."
    links:
      - twitter: "https://twitter.com/"
      - github: "https://github.com/sposusu"
  
  # Main sections for homepage
  mainSections: ["posts"]
  
  # Custom CSS
  customCSS: ["css/custom.css"]

# Menu
menu:
  main:
    - name: "Blog"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Categories" 
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4

# Taxonomies
taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"

# Pagination
pagination:
  pagerSize: 6
  path: 'page'

# Outputs
outputs:
  home: ["HTML", "RSS", "JSON"]

# Markdown
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true

# Static files
staticDir: ["static"]

# Build settings
publishDir: "public"

# Content
contentDir: "content"
layoutDir: "layouts"
dataDir: "data"

# Permalinks
permalinks:
  posts: "/:title/"