baseURL: 'https://sposusu.github.io'
languageCode: 'en-us'
title: 'Hussar place'
description: 'Record the exploration'

# Site settings
params:
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  description: 'Record the exploration'
  author: 'Hussar'
  
  # Analytics
  googleAnalytics: 'G-433XCR65EL'
  
  # Comments
  disqus:
    shortname: 'demowebsite'
  
  # Social
  mailchimp:
    list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
  
  # Features
  lazyImages: false

# Menu
menu:
  main:
    - name: "Blog"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Categories" 
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4

# Taxonomies
taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"

# Authors
params:
  authors:
    sal:
      name: "Sal"
      display_name: "Sal"
      email: "wowthemesnet@gmail.com"
      web: "https://www.wowthemes.net"
      twitter: "https://twitter.com/wowthemesnet"
      description: "Author of Mediumish, a Bootstrap Medium styled template."
      gravatar: "e56154546cf4be74e393c62d1ae9f9d4"
    john:
      name: "John"
      display_name: "John"
      email: "wowthemesnet@gmail.com"
      web: "https://www.wowthemes.net"
      twitter: "https://twitter.com/wowthemesnet"
      description: "This is the author box description."
      avatar: "images/avatar.png"
      gravatar: "b1cc14991db7a456fcd761680bbc8f81"
    paul:
      name: "Paul"
      display_name: "Paul"
      description: "Content contributor"

# Pagination
pagination:
  pagerSize: 6
  path: 'page'

# Markdown
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true

# Static files
staticDir: ["static", "assets"]

# Build settings
publishDir: "public"

# Content
contentDir: "content"
layoutDir: "layouts"
dataDir: "data"

# Permalinks
permalinks:
  posts: "/:title/"